#og_ttl <- jsonlite::fromJSON("http://rdf-translator.appspot.com/convert/detect/json-ld/ogp.me%2Fns%2Fogp.me.ttl")

c("article:author", "article:modified_time", "article:published_time",
"article:section", "article:tag", "book:author", "book:isbn",
"book:release_date", "book:tag", "country:allowed", "country:disallowed",
"fb:admins", "fb:app_id", "fb:pages", "fb:profile_id", "og:audio",
"og:audio:album", "og:audio:artist", "og:audio:secure_url", "og:audio:title",
"og:audio:type", "og:audio:url", "og:availability:destinations",
"og:brand", "og:country-name", "og:description", "og:determiner",
"og:email", "og:fax_number", "og:image", "og:image:height", "og:image:secure_url",
"og:image:type", "og:image:url", "og:image:width", "og:isbn",
"og:latitude", "og:locale", "og:locality", "og:longitude", "og:phone_number",
"og:postal-code", "og:rating", "og:rating_count", "og:rating_scale",
"og:referenced", "og:region", "og:restrictions:age", "og:restrictions:content",
"og:restrictions:country", "og:rich_attachment", "og:see_also",
"og:site_name", "og:street-address", "og:title", "og:ttl", "og:type",
"og:upc", "og:updated_time", "og:url", "og:video", "og:video:height",
"og:video:secure_url", "og:video:type", "og:video:url", "og:video:width",
"ogc:boolean_str", "ogc:date_time_str", "ogc:determiner_str",
"ogc:float_str", "ogc:integer_str", "ogc:mime_type_str", "ogc:string",
"ogc:url", "product:color", "product:color:image", "product:color:map",
"product:expiration_time", "product:gender", "profile:first_name",
"profile:gender", "profile:last_name", "profile:username", "twitter:app:id:googleplay",
"twitter:app:id:ipad", "twitter:app:id:iphone", "twitter:app:name:googleplay",
"twitter:app:name:ipad", "twitter:app:name:iphone", "twitter:app:url:googleplay",
"twitter:app:url:ipad", "twitter:app:url:iphone", "twitter:card",
"twitter:creator", "twitter:creator:id", "twitter:description",
"twitter:image", "twitter:image:alt", "twitter:player", "twitter:player:height",
"twitter:player:stream", "twitter:player:width", "twitter:site",
"twitter:site:id", "twitter:title", "video:director", "video:duration",
"video:release_date", "video:tag") -> .valid_properties
